[env:atmega88pv]
platform = atmelavr
board = atmega88pv
framework = arduino
board_build.f_cpu = 8000000L
upload_protocol = usbasp

upload_flags =
  -B 20
  -e
  -Ulock:w:0x3F:m
  -Uflash:w:.pio/build/atmega88pv/firmware.hex:i
  -Uflash:v:.pio/build/atmega88pv/firmware.hex:i

lib_deps =
  adafruit/Adafruit NeoPixel @ ^1.12.0